### ISSUE TITLE
Implementing REST API #1 blog

### ISSUE THREAD

**Issue by hvitis** [hvitis/Podcaster#3]
This issue is about implementing DRF
https://www.django-rest-framework.org/

In order to proceed with the roadmap of running the app with separate fron-end and not monolithic structure we need to start with implementing GET public endpoints.

The app will be used by 2 types of users:

- Readers/Listeners that should only have GET access and see the content
- Admin/Owner that should publish and edit.

We can preserve Admin ready to use Django´s Admin panel at
{{URL}}/admin
and proceed with just starting with a READ-only app.

So after adding DRF the endpoints should be created:

GET posts
GET posts/<id>

__with good practices__

https://hackernoon.com/restful-api-designing-guidelines-the-best-practices-60e1d954e7c9
https://swagger.io/blog/api-design/api-design-best-practices/

**Comment by lokeshramanav** [comment]
Created branch "Implementing-REST-API-#3"  and working on implementing the feature

**Comment by hvitis** [comment]
Hello @lokeshramanav 

I've updated the issue and narrowed the scope only to 
GET posts
GET posts/id

In case you did more please write it in the comment (I made a separate issues for others with with episodes, about etc)

Thank you! : 🙏

**Comment by hvitis** [comment]
@lokeshramanav this is done, moving to done.
